language: java
jdk: openjdk14

sudo: false

services:
  - postgresql

before_script:
  - psql -c 'create database forum;' -U postgres

install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - david.klarson@mail.ru
    on_success: never
    on_failure: always

env:
  global:
  - CODECOV_TOKEN="65da3349-cefd-4501-aa07-71efca6361f7"

